server:
  port: 8081
  tomcat:
    uri-encoding: utf-8
  servlet:
    session:
      timeout: 30m


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dbdatabase?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456


mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml